name: LeetCode Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      - run: yarn policies set-version 1.22.17
      - run: yarn ci
      - run: yarn run test
      - run: yarn run build
